/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dmich
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitDialogBox = new javax.swing.JDialog();
        exitConfirmTxt = new javax.swing.JLabel();
        exitYes = new javax.swing.JButton();
        exitNo = new javax.swing.JButton();
        loginDialogBox = new javax.swing.JDialog();
        loginTxt = new javax.swing.JLabel();
        positionSelection = new javax.swing.JComboBox();
        loginPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginSubmit = new javax.swing.JButton();
        loadingScreen = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        emergencyExit = new javax.swing.JButton();
        secretaryPage = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        supervisorPage = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        meterReaderPage = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        homePage = new javax.swing.JPanel();
        homePageTxt = new javax.swing.JLabel();
        homeLogin = new javax.swing.JButton();
        homeExit = new javax.swing.JButton();

        exitDialogBox.setTitle("Are you sure?");
        exitDialogBox.setAlwaysOnTop(true);
        exitDialogBox.setMinimumSize(new java.awt.Dimension(200, 100));

        exitConfirmTxt.setText("Are you sure you want to exit?");

        exitYes.setText("Yes");
        exitYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitYesActionPerformed(evt);
            }
        });

        exitNo.setText("No");
        exitNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exitDialogBoxLayout = new javax.swing.GroupLayout(exitDialogBox.getContentPane());
        exitDialogBox.getContentPane().setLayout(exitDialogBoxLayout);
        exitDialogBoxLayout.setHorizontalGroup(
            exitDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exitDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(exitDialogBoxLayout.createSequentialGroup()
                        .addComponent(exitYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitConfirmTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitDialogBoxLayout.setVerticalGroup(
            exitDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitConfirmTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(exitDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitYes)
                    .addComponent(exitNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginDialogBox.setPreferredSize(new java.awt.Dimension(455, 155));
        loginDialogBox.setResizable(false);
        loginDialogBox.setSize(new java.awt.Dimension(455, 155));

        loginTxt.setText("Please select your position from the drop-down box and provide your password.");

        positionSelection.setMaximumRowCount(3);
        positionSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Supervisor", "Secretary", "Meter Reader" }));

        loginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Password:");

        jLabel2.setText("Position:");

        loginSubmit.setText("Submit");
        loginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginDialogBoxLayout = new javax.swing.GroupLayout(loginDialogBox.getContentPane());
        loginDialogBox.getContentPane().setLayout(loginDialogBoxLayout);
        loginDialogBoxLayout.setHorizontalGroup(
            loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogBoxLayout.createSequentialGroup()
                .addGroup(loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginDialogBoxLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positionSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogBoxLayout.createSequentialGroup()
                                .addComponent(loginSubmit)
                                .addGap(24, 24, 24))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginTxt)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        loginDialogBoxLayout.setVerticalGroup(
            loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(loginSubmit)
                .addContainerGap())
        );

        loadingScreen.setMinimumSize(new java.awt.Dimension(400, 300));
        loadingScreen.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Loading...");

        emergencyExit.setText("Emergency Exit");
        emergencyExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loadingScreenLayout = new javax.swing.GroupLayout(loadingScreen.getContentPane());
        loadingScreen.getContentPane().setLayout(loadingScreenLayout);
        loadingScreenLayout.setHorizontalGroup(
            loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingScreenLayout.createSequentialGroup()
                .addGroup(loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loadingScreenLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3))
                    .addGroup(loadingScreenLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(emergencyExit)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        loadingScreenLayout.setVerticalGroup(
            loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingScreenLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(emergencyExit)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        secretaryPage.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel4.setText("Hello! This is the page for the secretary!");

        javax.swing.GroupLayout secretaryPageLayout = new javax.swing.GroupLayout(secretaryPage.getContentPane());
        secretaryPage.getContentPane().setLayout(secretaryPageLayout);
        secretaryPageLayout.setHorizontalGroup(
            secretaryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secretaryPageLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel4)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        secretaryPageLayout.setVerticalGroup(
            secretaryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secretaryPageLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel4)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        supervisorPage.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel5.setText("this is the supervisor page");

        javax.swing.GroupLayout supervisorPageLayout = new javax.swing.GroupLayout(supervisorPage.getContentPane());
        supervisorPage.getContentPane().setLayout(supervisorPageLayout);
        supervisorPageLayout.setHorizontalGroup(
            supervisorPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorPageLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel5)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        supervisorPageLayout.setVerticalGroup(
            supervisorPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorPageLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel5)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        meterReaderPage.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel6.setText("this is the meter reader page");

        javax.swing.GroupLayout meterReaderPageLayout = new javax.swing.GroupLayout(meterReaderPage.getContentPane());
        meterReaderPage.getContentPane().setLayout(meterReaderPageLayout);
        meterReaderPageLayout.setHorizontalGroup(
            meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meterReaderPageLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel6)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        meterReaderPageLayout.setVerticalGroup(
            meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meterReaderPageLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel6)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePageFrame");
        setName("HomePageFrame"); // NOI18N

        homePageTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        homePageTxt.setText("Valley Falls Water Association");

        homeLogin.setText("Login");
        homeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLoginActionPerformed(evt);
            }
        });

        homeExit.setText("Exit");
        homeExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(homePageTxt)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(homeLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePageTxt)
                .addGap(36, 36, 36)
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLogin)
                    .addComponent(homeExit))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeExitActionPerformed
        //shows dialog box
        exitDialogBox.setVisible(true);
    }//GEN-LAST:event_homeExitActionPerformed

    private void homeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLoginActionPerformed
        //make dialog box appear with dropdown box of position
        loginDialogBox.setVisible(true);
        //have user select their position and enter their password
        //when position/password combo is correct, send to their appropriate interfaces
    }//GEN-LAST:event_homeLoginActionPerformed

    private void exitNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitNoActionPerformed
        exitDialogBox.setVisible(false);
    }//GEN-LAST:event_exitNoActionPerformed

    private void exitYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitYesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitYesActionPerformed

    private void loginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordFieldActionPerformed

    private void loginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitActionPerformed
        homePage.setVisible(false);
        loginDialogBox.setVisible(false);
        loadingScreen.setVisible(true);
        switch (positionSelection.getSelectedItem().toString()) {
            case "Secretary":
                secretaryPage.setVisible(true);
                break;
            case "Supervisor":
                supervisorPage.setVisible(true);
                break;
            case "Meter Reader":
                meterReaderPage.setVisible(true);
                break;
        }
    }//GEN-LAST:event_loginSubmitActionPerformed

    private void emergencyExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_emergencyExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emergencyExit;
    private javax.swing.JLabel exitConfirmTxt;
    private javax.swing.JDialog exitDialogBox;
    private javax.swing.JButton exitNo;
    private javax.swing.JButton exitYes;
    private javax.swing.JButton homeExit;
    private javax.swing.JButton homeLogin;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel homePageTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JDialog loadingScreen;
    private javax.swing.JDialog loginDialogBox;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JButton loginSubmit;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JDialog meterReaderPage;
    private javax.swing.JComboBox positionSelection;
    private javax.swing.JDialog secretaryPage;
    private javax.swing.JDialog supervisorPage;
    // End of variables declaration//GEN-END:variables
}
