/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dmich
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitDialogBox = new javax.swing.JDialog();
        exitConfirmTxt = new javax.swing.JLabel();
        exitYes = new javax.swing.JButton();
        exitNo = new javax.swing.JButton();
        loginDialogBox = new javax.swing.JDialog();
        loginTxt = new javax.swing.JLabel();
        positionSelection = new javax.swing.JComboBox();
        loginPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginSubmit = new javax.swing.JButton();
        loadingScreen = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        emergencyExit = new javax.swing.JButton();
        secretaryPage = new javax.swing.JDialog();
        createAccountBtn = new javax.swing.JButton();
        viewAccountBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        accountNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        supervisorPage = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        meterReaderPage = new javax.swing.JDialog();
        meterEntryAccountNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        meterReading = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        meterReadingSubmit = new javax.swing.JButton();
        loadAccountInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedAccountInfo = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        createAccountPage = new javax.swing.JDialog();
        createAccountSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newAccountNumber = new javax.swing.JTextField();
        newAccountName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        newInitMeterReading = new javax.swing.JTextField();
        newUserDialogBox = new javax.swing.JDialog();
        newUserPosition = new javax.swing.JComboBox();
        newUserPassword = new javax.swing.JPasswordField();
        newUserConfirmPassword = new javax.swing.JPasswordField();
        newUserSubmit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        homePage = new javax.swing.JPanel();
        homePageTxt = new javax.swing.JLabel();
        homeLogin = new javax.swing.JButton();
        homeExit = new javax.swing.JButton();
        createNewUser = new javax.swing.JButton();

        exitDialogBox.setTitle("Are you sure?");
        exitDialogBox.setAlwaysOnTop(true);
        exitDialogBox.setMinimumSize(new java.awt.Dimension(200, 100));

        exitConfirmTxt.setText("Are you sure you want to exit?");

        exitYes.setText("Yes");
        exitYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitYesActionPerformed(evt);
            }
        });

        exitNo.setText("No");
        exitNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exitDialogBoxLayout = new javax.swing.GroupLayout(exitDialogBox.getContentPane());
        exitDialogBox.getContentPane().setLayout(exitDialogBoxLayout);
        exitDialogBoxLayout.setHorizontalGroup(
            exitDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exitDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(exitDialogBoxLayout.createSequentialGroup()
                        .addComponent(exitYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitConfirmTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitDialogBoxLayout.setVerticalGroup(
            exitDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitConfirmTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(exitDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitYes)
                    .addComponent(exitNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginDialogBox.setResizable(false);
        loginDialogBox.setSize(new java.awt.Dimension(455, 155));

        loginTxt.setText("Please select your position from the drop-down box and provide your password.");

        positionSelection.setMaximumRowCount(3);
        positionSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Supervisor", "Secretary", "Meter Reader" }));

        loginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Password:");

        jLabel2.setText("Position:");

        loginSubmit.setText("Submit");
        loginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginDialogBoxLayout = new javax.swing.GroupLayout(loginDialogBox.getContentPane());
        loginDialogBox.getContentPane().setLayout(loginDialogBoxLayout);
        loginDialogBoxLayout.setHorizontalGroup(
            loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogBoxLayout.createSequentialGroup()
                .addGroup(loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginDialogBoxLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positionSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogBoxLayout.createSequentialGroup()
                                .addComponent(loginSubmit)
                                .addGap(24, 24, 24))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginTxt)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        loginDialogBoxLayout.setVerticalGroup(
            loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(loginSubmit)
                .addContainerGap())
        );

        loadingScreen.setMinimumSize(new java.awt.Dimension(400, 300));
        loadingScreen.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Loading...");

        emergencyExit.setText("Emergency Exit");
        emergencyExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loadingScreenLayout = new javax.swing.GroupLayout(loadingScreen.getContentPane());
        loadingScreen.getContentPane().setLayout(loadingScreenLayout);
        loadingScreenLayout.setHorizontalGroup(
            loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingScreenLayout.createSequentialGroup()
                .addGroup(loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loadingScreenLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3))
                    .addGroup(loadingScreenLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(emergencyExit)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        loadingScreenLayout.setVerticalGroup(
            loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingScreenLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(emergencyExit)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        secretaryPage.setMinimumSize(new java.awt.Dimension(450, 400));

        createAccountBtn.setText("Create New Account");
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        viewAccountBtn.setText("View Account");
        viewAccountBtn.setToolTipText("");

        jLabel5.setText("Account #:");

        accountNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumActionPerformed(evt);
            }
        });

        jLabel4.setText("OTHER THINGS WITH COSTS AND SHIT");

        javax.swing.GroupLayout secretaryPageLayout = new javax.swing.GroupLayout(secretaryPage.getContentPane());
        secretaryPage.getContentPane().setLayout(secretaryPageLayout);
        secretaryPageLayout.setHorizontalGroup(
            secretaryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secretaryPageLayout.createSequentialGroup()
                .addGroup(secretaryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, secretaryPageLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(createAccountBtn))
                    .addGroup(secretaryPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(secretaryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(secretaryPageLayout.createSequentialGroup()
                                .addComponent(accountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewAccountBtn)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        secretaryPageLayout.setVerticalGroup(
            secretaryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secretaryPageLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(createAccountBtn)
                .addGap(18, 18, 18)
                .addGroup(secretaryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAccountBtn)
                    .addComponent(jLabel5)
                    .addComponent(accountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        supervisorPage.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel9.setText("what should the supervisor see.....");

        javax.swing.GroupLayout supervisorPageLayout = new javax.swing.GroupLayout(supervisorPage.getContentPane());
        supervisorPage.getContentPane().setLayout(supervisorPageLayout);
        supervisorPageLayout.setHorizontalGroup(
            supervisorPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorPageLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel9)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        supervisorPageLayout.setVerticalGroup(
            supervisorPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorPageLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel9)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        meterReaderPage.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel7.setText("Account #:");

        jLabel8.setText("Meter Reading:");

        meterReadingSubmit.setText("Submit");
        meterReadingSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterReadingSubmitActionPerformed(evt);
            }
        });

        loadAccountInfo.setText("Load Account Info");

        selectedAccountInfo.setColumns(20);
        selectedAccountInfo.setRows(5);
        selectedAccountInfo.setText("[selected account info]\n[past readings, expected usage, meter type(s), etc.]");
        jScrollPane1.setViewportView(selectedAccountInfo);

        jLabel6.setText("METER READER PAGE");

        javax.swing.GroupLayout meterReaderPageLayout = new javax.swing.GroupLayout(meterReaderPage.getContentPane());
        meterReaderPage.getContentPane().setLayout(meterReaderPageLayout);
        meterReaderPageLayout.setHorizontalGroup(
            meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meterReaderPageLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meterReading, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(meterEntryAccountNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadAccountInfo)
                .addGap(24, 24, 24))
            .addGroup(meterReaderPageLayout.createSequentialGroup()
                .addGroup(meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meterReaderPageLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(meterReadingSubmit))
                    .addGroup(meterReaderPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(meterReaderPageLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        meterReaderPageLayout.setVerticalGroup(
            meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meterReaderPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meterEntryAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(loadAccountInfo))
                .addGap(28, 28, 28)
                .addGroup(meterReaderPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meterReading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addComponent(meterReadingSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        createAccountPage.setMinimumSize(new java.awt.Dimension(400, 400));

        createAccountSubmit.setText("Submit");
        createAccountSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountSubmitActionPerformed(evt);
            }
        });

        jLabel10.setText("Name:");

        jLabel11.setText("Account #:");

        newAccountNumber.setEditable(false);
        newAccountNumber.setText("[acc. num. here]");

        jLabel12.setText("Meter Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Initial Meter Reading:");

        javax.swing.GroupLayout createAccountPageLayout = new javax.swing.GroupLayout(createAccountPage.getContentPane());
        createAccountPage.getContentPane().setLayout(createAccountPageLayout);
        createAccountPageLayout.setHorizontalGroup(
            createAccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createAccountSubmit)
                .addGap(46, 46, 46))
            .addGroup(createAccountPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createAccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(createAccountPageLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createAccountPageLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(createAccountPageLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newInitMeterReading))
                    .addGroup(createAccountPageLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        createAccountPageLayout.setVerticalGroup(
            createAccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createAccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(newAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createAccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(newAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createAccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createAccountPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(newInitMeterReading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(createAccountSubmit)
                .addGap(21, 21, 21))
        );

        newUserPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Supervisor", "Secretary", "Meter Reader" }));

        newUserSubmit.setText("Submit");
        newUserSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserSubmitActionPerformed(evt);
            }
        });

        jLabel14.setText("Position:");

        jLabel15.setText("Password:");

        jLabel16.setText("Confirm Password:");

        javax.swing.GroupLayout newUserDialogBoxLayout = new javax.swing.GroupLayout(newUserDialogBox.getContentPane());
        newUserDialogBox.getContentPane().setLayout(newUserDialogBoxLayout);
        newUserDialogBoxLayout.setHorizontalGroup(
            newUserDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserDialogBoxLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(newUserDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(newUserDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newUserConfirmPassword)
                    .addComponent(newUserPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newUserPassword))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(newUserDialogBoxLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(newUserSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newUserDialogBoxLayout.setVerticalGroup(
            newUserDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserDialogBoxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(newUserDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(newUserDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(newUserDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(35, 35, 35)
                .addComponent(newUserSubmit)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePageFrame");
        setName("HomePageFrame"); // NOI18N

        homePageTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        homePageTxt.setText("Valley Falls Water Association");

        homeLogin.setText("Login");
        homeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLoginActionPerformed(evt);
            }
        });

        homeExit.setText("Exit");
        homeExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeExitActionPerformed(evt);
            }
        });

        createNewUser.setText("Create New User");
        createNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(homePageTxt)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(homeLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createNewUser)
                .addGap(18, 18, 18)
                .addComponent(homeExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePageTxt)
                .addGap(36, 36, 36)
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLogin)
                    .addComponent(homeExit)
                    .addComponent(createNewUser))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeExitActionPerformed
        //shows dialog box
        exitDialogBox.setVisible(true);
    }//GEN-LAST:event_homeExitActionPerformed

    private void homeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLoginActionPerformed
        //make dialog box appear with dropdown box of position
        loginDialogBox.setVisible(true);
        //have user select their position and enter their password
        //when position/password combo is correct, send to their appropriate interfaces
    }//GEN-LAST:event_homeLoginActionPerformed

    private void exitNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitNoActionPerformed
        exitDialogBox.setVisible(false);
    }//GEN-LAST:event_exitNoActionPerformed

    private void exitYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitYesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitYesActionPerformed

    private void loginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordFieldActionPerformed

    private void loginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitActionPerformed
        homePage.setVisible(false);
        loginDialogBox.setVisible(false);
        loadingScreen.setVisible(true);
        switch (positionSelection.getSelectedItem().toString()) {
            case "Secretary":
                secretaryPage.setVisible(true);
                break;
            case "Supervisor":
                supervisorPage.setVisible(true);
                break;
            case "Meter Reader":
                meterReaderPage.setVisible(true);
                break;
        }
    }//GEN-LAST:event_loginSubmitActionPerformed

    private void emergencyExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_emergencyExitActionPerformed

    private void accountNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumActionPerformed

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        createAccountPage.setVisible(true);
    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void createAccountSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountSubmitActionPerformed
        //ADD NEW ACCOUNT TO ARRAY OF ACCOUNTS
        createAccountPage.setVisible(false);
    }//GEN-LAST:event_createAccountSubmitActionPerformed

    private void meterReadingSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterReadingSubmitActionPerformed
        //Do something with the information given.
    }//GEN-LAST:event_meterReadingSubmitActionPerformed

    private void createNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewUserActionPerformed
        newUserDialogBox.setVisible(true);
    }//GEN-LAST:event_createNewUserActionPerformed

    private void newUserSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserSubmitActionPerformed
        //ADD NEW USER TO ARRAY OF USERS
    }//GEN-LAST:event_newUserSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNum;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JDialog createAccountPage;
    private javax.swing.JButton createAccountSubmit;
    private javax.swing.JButton createNewUser;
    private javax.swing.JButton emergencyExit;
    private javax.swing.JLabel exitConfirmTxt;
    private javax.swing.JDialog exitDialogBox;
    private javax.swing.JButton exitNo;
    private javax.swing.JButton exitYes;
    private javax.swing.JButton homeExit;
    private javax.swing.JButton homeLogin;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel homePageTxt;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadAccountInfo;
    private javax.swing.JDialog loadingScreen;
    private javax.swing.JDialog loginDialogBox;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JButton loginSubmit;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JTextField meterEntryAccountNum;
    private javax.swing.JDialog meterReaderPage;
    private javax.swing.JTextField meterReading;
    private javax.swing.JButton meterReadingSubmit;
    private javax.swing.JTextField newAccountName;
    private javax.swing.JTextField newAccountNumber;
    private javax.swing.JTextField newInitMeterReading;
    private javax.swing.JPasswordField newUserConfirmPassword;
    private javax.swing.JDialog newUserDialogBox;
    private javax.swing.JPasswordField newUserPassword;
    private javax.swing.JComboBox newUserPosition;
    private javax.swing.JButton newUserSubmit;
    private javax.swing.JComboBox positionSelection;
    private javax.swing.JDialog secretaryPage;
    private javax.swing.JTextArea selectedAccountInfo;
    private javax.swing.JDialog supervisorPage;
    private javax.swing.JButton viewAccountBtn;
    // End of variables declaration//GEN-END:variables
}
